Location, Post Form, Styling
codeforbliss/BlissUI pull request #13
Opened 2024-07-27 22:59 UTC by qihongw08

### Changes

**Assets**
- Added styling to each individual components under assets folder 

**Services**
`LocationRequest.jsx` , `locationService.jsx` for location related logic 
`postService.jsx` for post related API calls 

**UX** 
- Modified `Login.jsx` when user is already logged in, auto direct to quotes page 
- Modifed `Quotes.jsx` to direct to login page if user is not logged in 

**`Posts.jsx` and `PostForm.jsx`**
- You can see all the posts in the Posts page
- You can post in the post form

2024-07-27 23:44 UTC, quntao-z requested changes

2024-07-27 23:44 UTC, quntao-z commented on src/components/Login.jsx
> +      console.log(user)
remove

2024-07-27 23:44 UTC, quntao-z commented on src/components/Login.jsx
> +        alert("welcome")
do we still need this?

2024-07-28 04:36 UTC, quntao-z requested changes

2024-07-28 04:36 UTC, quntao-z commented on src/common/BackendApi.js
> +const loggedUserJSON = window.localStorage.getItem("loggedUser");
Why don't we get token from user reducer here?

2024-07-28 04:36 UTC, quntao-z commented on src/components/PostForm.jsx
> +  const token = "Bearer " + useSelector((state) => state.user.token);
Can we handle this on the api side?

2024-07-30 23:58 UTC, qihongw08 commented on src/common/BackendApi.js
> +const loggedUserJSON = window.localStorage.getItem("loggedUser");
Backend Api is not used for now

2024-07-31 00:33 UTC, quntao-z requested changes

2024-07-31 00:33 UTC, quntao-z commented on src/reducer/userReducer.jsx
> +        quoteService.setToken(user.token);
PostService set token here as well

2024-07-31 00:57 UTC, quntao-z approved these changes

2024-08-01 03:55 UTC, merged